/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as ServicesCommercialMallCleaningRouteImport } from './routes/services.commercial-mall-cleaning'
import { Route as ServicesFactoryOfficeCleaningRouteImport } from './routes/services.factory-office-cleaning'
import { Route as ServicesHomeCleaningRouteImport } from './routes/services.home-cleaning'
import { Route as ServicesMoveInCleaningRouteImport } from './routes/services.move-in-cleaning'
import { Route as ServicesMoveOutCleaningRouteImport } from './routes/services.move-out-cleaning'
import { Route as ServicesPostRenovationCleaningRouteImport } from './routes/services.post-renovation-cleaning'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCommercialMallCleaningRoute =
  ServicesCommercialMallCleaningRouteImport.update({
    id: '/services/commercial-mall-cleaning',
    path: '/services/commercial-mall-cleaning',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesFactoryOfficeCleaningRoute =
  ServicesFactoryOfficeCleaningRouteImport.update({
    id: '/services/factory-office-cleaning',
    path: '/services/factory-office-cleaning',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesHomeCleaningRoute = ServicesHomeCleaningRouteImport.update({
  id: '/services/home-cleaning',
  path: '/services/home-cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMoveInCleaningRoute = ServicesMoveInCleaningRouteImport.update({
  id: '/services/move-in-cleaning',
  path: '/services/move-in-cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMoveOutCleaningRoute = ServicesMoveOutCleaningRouteImport.update({
  id: '/services/move-out-cleaning',
  path: '/services/move-out-cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPostRenovationCleaningRoute =
  ServicesPostRenovationCleaningRouteImport.update({
    id: '/services/post-renovation-cleaning',
    path: '/services/post-renovation-cleaning',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookings': typeof BookingsRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRoute
  '/services/commercial-mall-cleaning': typeof ServicesCommercialMallCleaningRoute
  '/services/factory-office-cleaning': typeof ServicesFactoryOfficeCleaningRoute
  '/services/home-cleaning': typeof ServicesHomeCleaningRoute
  '/services/move-in-cleaning': typeof ServicesMoveInCleaningRoute
  '/services/move-out-cleaning': typeof ServicesMoveOutCleaningRoute
  '/services/post-renovation-cleaning': typeof ServicesPostRenovationCleaningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookings': typeof BookingsRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRoute
  '/services/commercial-mall-cleaning': typeof ServicesCommercialMallCleaningRoute
  '/services/factory-office-cleaning': typeof ServicesFactoryOfficeCleaningRoute
  '/services/home-cleaning': typeof ServicesHomeCleaningRoute
  '/services/move-in-cleaning': typeof ServicesMoveInCleaningRoute
  '/services/move-out-cleaning': typeof ServicesMoveOutCleaningRoute
  '/services/post-renovation-cleaning': typeof ServicesPostRenovationCleaningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookings': typeof BookingsRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRoute
  '/services/commercial-mall-cleaning': typeof ServicesCommercialMallCleaningRoute
  '/services/factory-office-cleaning': typeof ServicesFactoryOfficeCleaningRoute
  '/services/home-cleaning': typeof ServicesHomeCleaningRoute
  '/services/move-in-cleaning': typeof ServicesMoveInCleaningRoute
  '/services/move-out-cleaning': typeof ServicesMoveOutCleaningRoute
  '/services/post-renovation-cleaning': typeof ServicesPostRenovationCleaningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bookings'
    | '/privacy'
    | '/reviews'
    | '/sitemap.xml'
    | '/thank-you'
    | '/services/commercial-mall-cleaning'
    | '/services/factory-office-cleaning'
    | '/services/home-cleaning'
    | '/services/move-in-cleaning'
    | '/services/move-out-cleaning'
    | '/services/post-renovation-cleaning'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bookings'
    | '/privacy'
    | '/reviews'
    | '/sitemap.xml'
    | '/thank-you'
    | '/services/commercial-mall-cleaning'
    | '/services/factory-office-cleaning'
    | '/services/home-cleaning'
    | '/services/move-in-cleaning'
    | '/services/move-out-cleaning'
    | '/services/post-renovation-cleaning'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bookings'
    | '/privacy'
    | '/reviews'
    | '/sitemap.xml'
    | '/thank-you'
    | '/services/commercial-mall-cleaning'
    | '/services/factory-office-cleaning'
    | '/services/home-cleaning'
    | '/services/move-in-cleaning'
    | '/services/move-out-cleaning'
    | '/services/post-renovation-cleaning'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingsRoute: typeof BookingsRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewsRoute: typeof ReviewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ThankYouRoute: typeof ThankYouRoute
  ServicesCommercialMallCleaningRoute: typeof ServicesCommercialMallCleaningRoute
  ServicesFactoryOfficeCleaningRoute: typeof ServicesFactoryOfficeCleaningRoute
  ServicesHomeCleaningRoute: typeof ServicesHomeCleaningRoute
  ServicesMoveInCleaningRoute: typeof ServicesMoveInCleaningRoute
  ServicesMoveOutCleaningRoute: typeof ServicesMoveOutCleaningRoute
  ServicesPostRenovationCleaningRoute: typeof ServicesPostRenovationCleaningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/commercial-mall-cleaning': {
      id: '/services/commercial-mall-cleaning'
      path: '/services/commercial-mall-cleaning'
      fullPath: '/services/commercial-mall-cleaning'
      preLoaderRoute: typeof ServicesCommercialMallCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/factory-office-cleaning': {
      id: '/services/factory-office-cleaning'
      path: '/services/factory-office-cleaning'
      fullPath: '/services/factory-office-cleaning'
      preLoaderRoute: typeof ServicesFactoryOfficeCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/home-cleaning': {
      id: '/services/home-cleaning'
      path: '/services/home-cleaning'
      fullPath: '/services/home-cleaning'
      preLoaderRoute: typeof ServicesHomeCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/move-in-cleaning': {
      id: '/services/move-in-cleaning'
      path: '/services/move-in-cleaning'
      fullPath: '/services/move-in-cleaning'
      preLoaderRoute: typeof ServicesMoveInCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/move-out-cleaning': {
      id: '/services/move-out-cleaning'
      path: '/services/move-out-cleaning'
      fullPath: '/services/move-out-cleaning'
      preLoaderRoute: typeof ServicesMoveOutCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/post-renovation-cleaning': {
      id: '/services/post-renovation-cleaning'
      path: '/services/post-renovation-cleaning'
      fullPath: '/services/post-renovation-cleaning'
      preLoaderRoute: typeof ServicesPostRenovationCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingsRoute: BookingsRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewsRoute: ReviewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ThankYouRoute: ThankYouRoute,
  ServicesCommercialMallCleaningRoute: ServicesCommercialMallCleaningRoute,
  ServicesFactoryOfficeCleaningRoute: ServicesFactoryOfficeCleaningRoute,
  ServicesHomeCleaningRoute: ServicesHomeCleaningRoute,
  ServicesMoveInCleaningRoute: ServicesMoveInCleaningRoute,
  ServicesMoveOutCleaningRoute: ServicesMoveOutCleaningRoute,
  ServicesPostRenovationCleaningRoute: ServicesPostRenovationCleaningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
