/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ServicesCommercialMallCleaningRouteImport } from './routes/services.commercial-mall-cleaning'
import { Route as ServicesFactoryOfficeCleaningRouteImport } from './routes/services.factory-office-cleaning'
import { Route as ServicesHomeCleaningRouteImport } from './routes/services.home-cleaning'
import { Route as ServicesMoveInMoveOutCleaningRouteImport } from './routes/services.move-in-move-out-cleaning'
import { Route as ServicesPostRenovationCleaningRouteImport } from './routes/services.post-renovation-cleaning'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCommercialMallCleaningRoute =
  ServicesCommercialMallCleaningRouteImport.update({
    id: '/services/commercial-mall-cleaning',
    path: '/services/commercial-mall-cleaning',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesFactoryOfficeCleaningRoute =
  ServicesFactoryOfficeCleaningRouteImport.update({
    id: '/services/factory-office-cleaning',
    path: '/services/factory-office-cleaning',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesHomeCleaningRoute = ServicesHomeCleaningRouteImport.update({
  id: '/services/home-cleaning',
  path: '/services/home-cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMoveInMoveOutCleaningRoute =
  ServicesMoveInMoveOutCleaningRouteImport.update({
    id: '/services/move-in-move-out-cleaning',
    path: '/services/move-in-move-out-cleaning',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesPostRenovationCleaningRoute =
  ServicesPostRenovationCleaningRouteImport.update({
    id: '/services/post-renovation-cleaning',
    path: '/services/post-renovation-cleaning',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRoute
  '/welcome': typeof WelcomeRoute
  '/services/commercial-mall-cleaning': typeof ServicesCommercialMallCleaningRoute
  '/services/factory-office-cleaning': typeof ServicesFactoryOfficeCleaningRoute
  '/services/home-cleaning': typeof ServicesHomeCleaningRoute
  '/services/move-in-move-out-cleaning': typeof ServicesMoveInMoveOutCleaningRoute
  '/services/post-renovation-cleaning': typeof ServicesPostRenovationCleaningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRoute
  '/welcome': typeof WelcomeRoute
  '/services/commercial-mall-cleaning': typeof ServicesCommercialMallCleaningRoute
  '/services/factory-office-cleaning': typeof ServicesFactoryOfficeCleaningRoute
  '/services/home-cleaning': typeof ServicesHomeCleaningRoute
  '/services/move-in-move-out-cleaning': typeof ServicesMoveInMoveOutCleaningRoute
  '/services/post-renovation-cleaning': typeof ServicesPostRenovationCleaningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRoute
  '/welcome': typeof WelcomeRoute
  '/services/commercial-mall-cleaning': typeof ServicesCommercialMallCleaningRoute
  '/services/factory-office-cleaning': typeof ServicesFactoryOfficeCleaningRoute
  '/services/home-cleaning': typeof ServicesHomeCleaningRoute
  '/services/move-in-move-out-cleaning': typeof ServicesMoveInMoveOutCleaningRoute
  '/services/post-renovation-cleaning': typeof ServicesPostRenovationCleaningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/sitemap.xml'
    | '/thank-you'
    | '/welcome'
    | '/services/commercial-mall-cleaning'
    | '/services/factory-office-cleaning'
    | '/services/home-cleaning'
    | '/services/move-in-move-out-cleaning'
    | '/services/post-renovation-cleaning'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/sitemap.xml'
    | '/thank-you'
    | '/welcome'
    | '/services/commercial-mall-cleaning'
    | '/services/factory-office-cleaning'
    | '/services/home-cleaning'
    | '/services/move-in-move-out-cleaning'
    | '/services/post-renovation-cleaning'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/sitemap.xml'
    | '/thank-you'
    | '/welcome'
    | '/services/commercial-mall-cleaning'
    | '/services/factory-office-cleaning'
    | '/services/home-cleaning'
    | '/services/move-in-move-out-cleaning'
    | '/services/post-renovation-cleaning'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ThankYouRoute: typeof ThankYouRoute
  WelcomeRoute: typeof WelcomeRoute
  ServicesCommercialMallCleaningRoute: typeof ServicesCommercialMallCleaningRoute
  ServicesFactoryOfficeCleaningRoute: typeof ServicesFactoryOfficeCleaningRoute
  ServicesHomeCleaningRoute: typeof ServicesHomeCleaningRoute
  ServicesMoveInMoveOutCleaningRoute: typeof ServicesMoveInMoveOutCleaningRoute
  ServicesPostRenovationCleaningRoute: typeof ServicesPostRenovationCleaningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/commercial-mall-cleaning': {
      id: '/services/commercial-mall-cleaning'
      path: '/services/commercial-mall-cleaning'
      fullPath: '/services/commercial-mall-cleaning'
      preLoaderRoute: typeof ServicesCommercialMallCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/factory-office-cleaning': {
      id: '/services/factory-office-cleaning'
      path: '/services/factory-office-cleaning'
      fullPath: '/services/factory-office-cleaning'
      preLoaderRoute: typeof ServicesFactoryOfficeCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/home-cleaning': {
      id: '/services/home-cleaning'
      path: '/services/home-cleaning'
      fullPath: '/services/home-cleaning'
      preLoaderRoute: typeof ServicesHomeCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/move-in-move-out-cleaning': {
      id: '/services/move-in-move-out-cleaning'
      path: '/services/move-in-move-out-cleaning'
      fullPath: '/services/move-in-move-out-cleaning'
      preLoaderRoute: typeof ServicesMoveInMoveOutCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/post-renovation-cleaning': {
      id: '/services/post-renovation-cleaning'
      path: '/services/post-renovation-cleaning'
      fullPath: '/services/post-renovation-cleaning'
      preLoaderRoute: typeof ServicesPostRenovationCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ThankYouRoute: ThankYouRoute,
  WelcomeRoute: WelcomeRoute,
  ServicesCommercialMallCleaningRoute: ServicesCommercialMallCleaningRoute,
  ServicesFactoryOfficeCleaningRoute: ServicesFactoryOfficeCleaningRoute,
  ServicesHomeCleaningRoute: ServicesHomeCleaningRoute,
  ServicesMoveInMoveOutCleaningRoute: ServicesMoveInMoveOutCleaningRoute,
  ServicesPostRenovationCleaningRoute: ServicesPostRenovationCleaningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
